export const proyectos = [
  {
    id: 1,
    nombre: "Desarrollo de App Móvil Multiplataforma",
    dificultad: "alta",
    tareas: [
      {
        id: 1,
        nombre: "Definir requisitos funcionales",
        avance: 100,
        dificultad: "baja",
      },
      {
        id: 2,
        nombre: "Diseñar interfaz de usuario (UI/UX)",
        avance: 80,
        dificultad: "media",
      },
      {
        id: 3,
        nombre: "Configurar entorno de desarrollo",
        avance: 100,
        dificultad: "baja",
      },
      {
        id: 4,
        nombre: "Implementar autenticación de usuarios",
        avance: 60,
        dificultad: "media",
      },
      {
        id: 5,
        nombre: "Desarrollar pantalla principal",
        avance: 40,
        dificultad: "alta",
      },
      { id: 6, nombre: "Pruebas unitarias", avance: 0, dificultad: "alta" },
      {
        id: 7,
        nombre: "Documentación técnica y manual de usuario",
        avance: 0,
        dificultad: "baja",
      },
    ],
  },
  {
    id: 2,
    nombre: "Migración de Base de Datos a la Nube",
    dificultad: "media",
    tareas: [
      {
        id: 1,
        nombre: "Evaluar proveedor de nube (AWS, GCP, Azure)",
        avance: 100,
        dificultad: "baja",
      },
      {
        id: 2,
        nombre: "Realizar copia de seguridad local",
        avance: 100,
        dificultad: "baja",
      },
      {
        id: 3,
        nombre: "Diseñar esquema de base de datos en la nube",
        avance: 90,
        dificultad: "media",
      },
      {
        id: 4,
        nombre: "Migrar datos desde servidor local",
        avance: 70,
        dificultad: "media",
      },
      {
        id: 5,
        nombre: "Configurar acceso remoto seguro",
        avance: 50,
        dificultad: "media",
      },
      {
        id: 6,
        nombre: "Optimizar consultas SQL",
        avance: 30,
        dificultad: "alta",
      },
      {
        id: 7,
        nombre: "Validar integridad de datos migrados",
        avance: 0,
        dificultad: "baja",
      },
    ],
  },
  {
    id: 3,
    nombre: "Implementación de Sistema de Gestión de Proyectos (Kanban)",
    dificultad: "media",
    tareas: [
      {
        id: 1,
        nombre: "Investigar herramientas disponibles (Trello, Jira, Asana)",
        avance: 100,
        dificultad: "baja",
      },
      {
        id: 2,
        nombre: "Seleccionar e instalar herramienta elegida",
        avance: 100,
        dificultad: "baja",
      },
      {
        id: 3,
        nombre: "Crear tablero Kanban personalizado",
        avance: 90,
        dificultad: "media",
      },
      {
        id: 4,
        nombre: "Integrar con repositorio de código fuente",
        avance: 70,
        dificultad: "media",
      },
      {
        id: 5,
        nombre: "Capacitar al equipo en el uso de la herramienta",
        avance: 60,
        dificultad: "baja",
      },
      {
        id: 6,
        nombre: "Automatizar flujos de trabajo",
        avance: 40,
        dificultad: "alta",
      },
      {
        id: 7,
        nombre: "Generar reportes de rendimiento del equipo",
        avance: 0,
        dificultad: "media",
      },
    ],
  },
  {
    id: 4,
    nombre: "Creación de API RESTful para una Plataforma E-learning",
    dificultad: "alta",
    tareas: [
      {
        id: 1,
        nombre: "Definir endpoints y estructura de datos",
        avance: 100,
        dificultad: "baja",
      },
      {
        id: 2,
        nombre: "Configurar entorno backend (Node.js / Express)",
        avance: 100,
        dificultad: "baja",
      },
      {
        id: 3,
        nombre: "Implementar sistema de autenticación JWT",
        avance: 80,
        dificultad: "media",
      },
      {
        id: 4,
        nombre: "Conectar con base de datos (MongoDB o PostgreSQL)",
        avance: 80,
        dificultad: "media",
      },
      {
        id: 5,
        nombre: "Desarrollar CRUD para módulos de cursos",
        avance: 60,
        dificultad: "alta",
      },
      {
        id: 6,
        nombre: "Probar endpoints con Postman",
        avance: 50,
        dificultad: "media",
      },
      {
        id: 7,
        nombre: "Documentar API con Swagger/OpenAPI",
        avance: 40,
        dificultad: "baja",
      },
    ],
  },
  {
    id: 5,
    nombre: "Despliegue Continuo con CI/CD en GitHub Actions",
    dificultad: "alta",
    tareas: [
      {
        id: 1,
        nombre: "Preparar repositorio de GitHub",
        avance: 100,
        dificultad: "baja",
      },
      {
        id: 2,
        nombre: "Escribir archivo de configuración .yml para GitHub Actions",
        avance: 90,
        dificultad: "media",
      },
      {
        id: 3,
        nombre: "Configurar pruebas automáticas (unit testing)",
        avance: 80,
        dificultad: "alta",
      },
      {
        id: 4,
        nombre: "Desplegar en servidor de staging",
        avance: 70,
        dificultad: "alta",
      },
      {
        id: 5,
        nombre: "Integrar notificaciones por correo/slack",
        avance: 60,
        dificultad: "media",
      },
      {
        id: 6,
        nombre: "Establecer rollback automático ante fallos",
        avance: 50,
        dificultad: "alta",
      },
      {
        id: 7,
        nombre: "Monitoreo continuo y logs",
        avance: 0,
        dificultad: "alta",
      },
    ],
  },
];
